[package]
name = "harmony"
version = "0.1.0"
authors = ["John Mitchell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
arrayvec = "0.5.1"
env_logger = "0.7.1"
futures = "0.3"
gltf="0.15.2"
glyph_brush = "0.6"
image = "0.23.3"
log = "0.4"
nalgebra = "0.21.0"
nalgebra-glm = "0.7"
shaderc = "0.6"
specs = "0.16.1"
stretch = "0.3.2"
walkdir = "2"
wgpu = { git="https://github.com/StarArawn/wgpu-rs", rev="5234df523d621ae9745aca0ae9f7c10b69f66546" }
wgpu_glyph = { git="https://github.com/StarArawn/wgpu_glyph", branch="master" }
winit = { version = "0.22.0", features = ["web-sys"] }
zerocopy = "0.3"
bytemuck = { version = "1.2.0", features = ["extern_crate_alloc"] }

[patch.crates-io]
wgpu = { git="https://github.com/StarArawn/wgpu-rs", rev="5234df523d621ae9745aca0ae9f7c10b69f66546" }
# wgpu-core = { git = "https://github.com/gfx-rs/wgpu", rev = "daf45362bcfc9d012003b498e94888366efd2f5b" }
# wgpu-types = { git = "https://github.com/gfx-rs/wgpu", rev = "daf45362bcfc9d012003b498e94888366efd2f5b" }
# wgpu-native = { git = "https://github.com/gfx-rs/wgpu", rev = "daf45362bcfc9d012003b498e94888366efd2f5b" }
