[package]
name = "harmony"
version = "0.1.0"
authors = ["John Mitchell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
arrayvec = "0.5.1"
futures = "0.3"
shaderc = "0.6"
walkdir = "2"
wgpu = { git="https://github.com/gfx-rs/wgpu-rs", branch="master" }
winit = { version = "0.22.0", features = ["web-sys"] }
ultraviolet = "0.4.5"
zerocopy = "0.3"