[package]
name = "harmony"
version = "0.1.0"
authors = ["John Mitchell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
arrayvec = "0.5.1"
env_logger = "0.7.1"
futures = "0.3"
gltf="0.15.2"
glyph_brush = "0.6"
image = "0.23.3"
log = "0.4"
nalgebra = "0.21.0"
nalgebra-glm = "0.7"
shaderc = "0.6"
specs = "0.16.1"
stretch = "0.3.2"
walkdir = "2"
wgpu = { path = "../wgpu-rs" }
# wgpu-native = { git="https://github.com/kvark/wgpu/", branch="swapchain-op"}
# wgpu-types = { git="https://github.com/kvark/wgpu/", branch="swapchain-op"}
# wgpu-core = { git="https://github.com/kvark/wgpu/", branch="swapchain-op"} #{ version = "0.5.2" }
wgpu_glyph = { git="https://github.com/hecrj/wgpu_glyph", branch="update-wgpu" }
winit = { version = "0.22.0", features = ["web-sys"] }
zerocopy = "0.3"
bytemuck = { version = "1.2.0", features = ["extern_crate_alloc"] }

[patch.crates-io]
wgpu = { path = "../wgpu-rs" }
